// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using integracaoLeads2b.Persistence;

#nullable disable

namespace integracaoLeads2b.Migrations
{
    [DbContext(typeof(LeadsDbContext))]
    [Migration("20240425003034_FixLeadsFieldsMigration")]
    partial class FixLeadsFieldsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("integracaoLeads2b.Entities.Leads", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Customer_company_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Customer_id")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Customer_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fk_id")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Lead_created_at")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Lead_Created_at");

                    b.Property<string>("Lead_id")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Lead_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lead_responsable")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lead_responsable_id")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Lead_status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("List_id")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Loss_reason")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lost_at")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Main_contact")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Main_email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Main_phone")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Opportunity_created_at")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Opportunity_id")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Opportunity_status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Order_date")
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("Order_total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pipeline")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pipeline_step")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("integracaoLeads2b.Entities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contact_address")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact_city")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact_cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Contact_complement")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact_email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact_list_id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact_neighborhood")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact_number")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Contact_state")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Contact_street")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Customer_address")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Customer_city")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Customer_complement")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Customer_id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Customer_neighborhood")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Customer_number")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Customer_state")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Expected_close_date")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lead_id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lead_responsible")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lead_responsible_id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lead_status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Loss_details")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Loss_reason")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lost_at")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Opportunity_created_at")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Opportunity_created_by")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Opportunity_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opportunity_responsible")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Opportunity_status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Opportunity_updated_at")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pipeline")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pipeline_step")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rdstation_uuid")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Reactived_at")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Opportunity");
                });

            modelBuilder.Entity("integracaoLeads2b.Entities.Prospect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Company_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Custom_fields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deleted_at")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Department")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Enriched")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enriched_at")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exclusion_reason")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fk_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("List_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loss_reason")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lost_at")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Main_contact")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Main_email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Main_phone")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Origin")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pipeline")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pipeline_step")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prospect_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prospect_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prospect_responsable")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prospect_responsable_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Social_reason")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Street")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tags")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Prospects");
                });
#pragma warning restore 612, 618
        }
    }
}
